export const ROUTES = {
    home: '/',
    login: '/login',
    plants: '/plants/page/',
    gallery: '/plant/gallery',
    search: '/plant/searcher',
    details: '/plant/details/',
    maintenance: '/maintenance',
    configs: '/configurations',
    create: '/admin/plant/create/new',
    admin: '/admin/plants',
    updatePlant: '/admin/update/plants/:id',
    update: '/admin/update/plants/',
    searchs: '/admin/search/list',
};