# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Write file with private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ../key.pem
    - name: Change permissions to key.pem
      run: chmod 400 ../key.pem
    - name: Check current directory content
      run: ls -a

    - name: Removing /tmp directory if present
      run: ssh -o StrictHostKeyChecking=no -i ../key.pem root@${{ secrets.SSH_HOST }} "cd /var/www/html/plants/ && rm -rf ./tmp"
    - name: Cloning the repository
      run: ssh -o StrictHostKeyChecking=no -i ../key.pem root@${{ secrets.SSH_HOST }} "cd /var/www/html/plants/ && git clone https://github.com/DavidFFDAW/Plants-App.git tmp"
    - name: Removing .git
      run: ssh -o StrictHostKeyChecking=no -i ../key.pem root@${{ secrets.SSH_HOST }} "cd /var/www/html/plants/tmp/ && rm -rf .git"
    - name: Moving backend api to folder
      run: ssh -o StrictHostKeyChecking=no -i ../key.pem root@${{ secrets.SSH_HOST }} "cd /var/www/html/plants/tmp/ && cp -R ./api/* /var/www/html/plants/api/ && rm -rf /var/www/html/plants/tmp/api/"
    - name: Moving frontend to folder 
      run: ssh -o StrictHostKeyChecking=no -i ../key.pem root@${{ secrets.SSH_HOST }} "cd /var/www/html/plants/tmp/ && cp -R ./frontend/* /var/www/html/plants/frontend/ && rm -rf /var/www/html/plants/tmp/frontend/"
    - name: Executing frontend container 
      run: ssh -o StrictHostKeyChecking=no -i ../key.pem root@${{ secrets.SSH_HOST }} "cd /var/www/html/plants/frontend && sh docker.sh"
    - name: Deleting tmp dir
      run: ssh -o StrictHostKeyChecking=no -i ../key.pem root@${{ secrets.SSH_HOST }} "cd /var/www/html/plants/ && rm -rf tmp/"


